#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Arrêt du service..." --weight=1
ynh_systemd_action --service_name="$app" --action="stop"
yunohost service remove "$app"

ynh_script_progression --message="Suppression des fichiers..." --weight=2
ynh_remove_systemd_config
ynh_remove_nginx_config
ynh_secure_remove --file="$install_dir"
# data_dir est conservé volontairement pour ne pas perdre les sessions

ynh_script_progression --message="Désinstallation terminée !" --last
