#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Arrêt du service..." --weight=1
ynh_systemd_action --service_name="$app" --action="stop"

ynh_script_progression --message="Mise à jour des sources..." --weight=3
ynh_setup_source --dest_dir="$install_dir" --keep="app/config.py"

ynh_script_progression --message="Mise à jour des dépendances Python..." --weight=3
"$install_dir/venv/bin/pip" install --upgrade flask gunicorn

ynh_script_progression --message="Mise à jour de la configuration NGINX..." --weight=1
ynh_add_nginx_config

ynh_script_progression --message="Mise à jour du service systemd..." --weight=1
ynh_add_systemd_config

chown -R "$app:$app" "$install_dir"

ynh_script_progression --message="Redémarrage du service..." --weight=1
ynh_systemd_action --service_name="$app" --action="start"

ynh_script_progression --message="Mise à jour terminée !" --last
